abbr --add deactivate "pyenv deactivate"
abbr --add fastapi "python -m uvicorn main:app --reload"
abbr --add mkvirtualenv "pyenv virtualenv"
abbr --add pi "python -m pip install"
abbr --add pylist "pyenv virtualenvs"
abbr --add pytest "python -m pytest"
abbr --add rmvirtualenv "pyenv uninstall"
# w means workon
abbr --add w "pyenv activate"
abbr --add jupyterlab "python -m jupyterlab --no-browser"
