repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    # Remove unused python imports
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
        args: [--in-place, --remove-all-unused-imports]
        exclude: "conftest.py|test_default.py|setup.py"
    # Sort python imports
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        # never remove --profile black
        # if you do that black/darker and isort will enter
        # in conflict and you'll enter in a infinity import
        # error because black will revert what isort fixed.
        args: ["--profile", "black"]
        exclude: "conftest.py|test_default.py|setup.py"
    # black but powered with diff
-   repo: https://github.com/akaihola/darker
    rev: 1.7.2
    hooks:
    -   id: darker
        exclude: "conftest.py|test_default.py|setup.py"
