#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=30 blur_radius=30 color=0x40000000

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# -- Left side items --
sketchybar --add item front_app left \
           --set front_app script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# -- Right side items --
sketchybar --add item battery right \
           --set battery update_freq=120 \
           script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

sketchybar --add item calendar right \
           --set calendar icon=􀉉 \
           update_freq=30 \
           script="$PLUGIN_DIR/calendar.sh"

sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
