[general]
import = [
  "~/.config/alacritty/color-schema.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 19.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.offset]
y = 1

[window]
option_as_alt = "Both"
decorations = "Buttonless"
